### ISSUE TITLE
老哥能帮忙看下怎么解决吗？

### ISSUE THREAD

**Issue by Zhangtaiy** [Seeyou66/ttl#2]
Traceback (most recent call last):
  File "/ql/scripts/raw_main_ttl_gift.py", line 21, in <module>
    from sendnotice import send
ModuleNotFoundError: No module named 'sendnotice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/scripts/raw_main_ttl_gift.py", line 23, in <module>
    from Seeyou66_ttl_sendnotice import send
ModuleNotFoundError: No module named 'Seeyou66_ttl_sendnotice'

**Comment by Seeyou66** [comment]
我更新下脚本，晚点拉取就好了

**Comment by Zhangtaiy** [comment]
好的，感谢> 我更新下脚本，晚点拉取就好了
